name: Publish container image to GHCR

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ghcr.io/canonical/jepsen-dqlite-unofficial:latest .

      - name: Push
        run: |
          docker push ghcr.io/canonical/jepsen-dqlite-unofficial:latest
