name: Dqlite Jepsen tests
on:
    push:
    pull_request:
    schedule:
      - cron: "0 */6 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        workload:
          - append
        nemesis:
          - partition
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3

    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y gnuplot libsqlite3-dev libuv1-dev liblz4-dev libjna-java graphviz leiningen build-essential ntpdate
        printf '/opt/dqlite/core' | sudo tee /proc/sys/kernel/core_pattern

    - name: Build raft
      run: |
          git clone https://github.com/Canonical/raft.git --depth 1
          cd raft
          git log -n 1
          autoreconf -i
          ./configure --enable-debug
          make -j4
          sudo make install
          cd ..

    - name: Build dqlite
      run: |
          git clone https://github.com/MathieuBordere/dqlite.git --depth 1 --single-branch --branch disk-mode-force
          cd dqlite
          git log -n 1
          autoreconf -i
          ./configure --enable-debug
          make -j4
          sudo make install
          cd ..

    - name: Test
      env:
        CGO_LDFLAGS_ALLOW: "-Wl,-z,now"
        LD_LIBRARY_PATH: "/usr/local/lib"
      timeout-minutes: 8
      run: |
        sudo ldconfig
        go get golang.org/x/sync/semaphore
        go get -tags libsqlite3 github.com/canonical/go-dqlite/app
        go build -tags libsqlite3 -o resources/app resources/app.go

    - name: Upterm
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: false

