name: Dqlite Jepsen tests
on:
    push:
    pull_request:
    schedule:
      - cron: "0 */6 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        workload:
          - append
          - set
          - bank
        nemesis:
          - partition
          - kill
          - stop
          - disk
          - member
          - partition,kill,stop
          - partition,kill,disk
          - partition,kill,member
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3

    - name: Setup environment
      run: |
        sudo apt install ubuntu-dbgsym-keyring
        echo deb http://ddebs.ubuntu.com focal main | sudo tee /etc/apt/sources.list.d/ddebs.list
        sudo apt update
        sudo apt install -y --allow-downgrades gnuplot sqlite3=3.31.1-4 libsqlite3-0=3.31.1-4 libsqlite3-dev=3.31.1-4 libuv1=1.34.2-1ubuntu1 libuv1-dev=1.34.2-1ubuntu1 liblz4-dev libjna-java graphviz leiningen build-essential ntpdate sqlite3-dbgsym libuv1-dbgsym
        printf '/opt/dqlite/core' | sudo tee /proc/sys/kernel/core_pattern
    - name: Install libbacktrace
      run: |
        git clone https://github.com/ianlancetaylor/libbacktrace --depth 1
        cd libbacktrace
        autoreconf -i
        ./configure
        make -j4
        sudo make install
        sudo ldconfig
        cd ..

    - name: Build raft
      run: |
          git clone https://github.com/Canonical/raft.git --depth 1
          cd raft
          git log -n 1
          autoreconf -i
          ./configure --enable-debug --enable-backtrace
          make -j4
          sudo make install
          cd ..

    - name: Build dqlite
      run: |
          git clone https://github.com/Canonical/dqlite.git --depth 1
          cd dqlite
          git log -n 1
          autoreconf -i
          ./configure --enable-debug --enable-backtrace
          make -j4
          sudo make install
          cd ..

    - name: Test
      env:
        CGO_LDFLAGS_ALLOW: "-Wl,-z,now"
        LD_LIBRARY_PATH: "/usr/local/lib"
      timeout-minutes: 8
      run: |
        sudo ldconfig
        go get golang.org/x/sync/semaphore
        go get -tags libsqlite3 github.com/canonical/go-dqlite/app
        go build -tags libsqlite3 -o resources/app resources/app.go
        sudo ufw disable
        sudo systemctl stop ufw.service
        # Make resolv.conf a real file so we can bind mount it in the namespace
        cp /etc/resolv.conf resolv.conf.tmp
        sudo rm /etc/resolv.conf
        sudo mv resolv.conf.tmp /etc/resolv.conf
        sudo iptables -w -t nat -A POSTROUTING -s 10.2.1.0/24 -d 0.0.0.0/0 -j MASQUERADE
        sudo ./resources/network.sh setup 5
        lein run test --no-ssh --binary $(pwd)/resources/app --workload ${{ matrix.workload }} --time-limit 240 --nemesis ${{ matrix.nemesis }} --rate 100
        sudo ./resources/network.sh teardown 5

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: jepsen-data-${{ matrix.workload }}-${{ matrix.nemesis }}
        path: store/dqlite*
