name: Dqlite Jepsen tests - expected fail

on:
  schedule:
    - cron: '30 */1 * * *'
  workflow_dispatch:
    inputs:
      raft-repo:
        description: Raft Repo
        default: canonical/raft
      raft-ref:
        description: raft branch or ref
        default: master
      dqlite-repo:
        description: Dqlite Repo
        default: canonical/dqlite
      dqlite-ref:
        description: dqlite branch or ref
        default: master

jobs:
  expected-fail:
    uses: canonical/jepsen.dqlite/.github/workflows/test-build-run.yml@master
    with:
      workloads: >
        [ 'bank', 'set' ]
      nemeses: >
        [ 'partition,disk',
          'pause,disk' ]
      disk: >
        [ '1' ]
      jepsen-dqlite-repo: ${{ github.repository }}
      jepsen-dqlite-ref: ${{ github.ref }}
      raft-repo: ${{ inputs.raft-repo || 'canonical/raft' }}
      raft-ref: ${{ inputs.raft-ref || 'master' }}
      dqlite-repo: ${{ inputs.dqlite-repo || 'canonical/dqlite' }}
      dqlite-ref: ${{ inputs.dqlite-ref || 'master' }}
